version: '3.9'

services:
  backend:
    build: .
    container_name: rolealchemy-backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:13
    container_name: rolealchemy-db
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: rolealchemy_developer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
